### ISSUE TITLE
json.decoder.JSONDecodeError при вызове video.update

### ISSUE THREAD

**Issue by RankoR** [alternativshik/python-odnoklassniki#8]
```
ok_client.video.update(
    vid=video_id,
    title='Test',
    description='Test description',
    tags='news',
    cover_photo_id=photo_id,
    cover_photo_upload_token=photo_upload_token,
    cid='<erased>'
)
```

Запрос проходит успешно (видео обновляется с заданными параметрами), но ответ не парсится:

```
Traceback (most recent call last):
  File "/Users/rankor/src/python/VideoMaker2/utils/demo/ok_demo.py", line 78, in <module>
    cid='c2360471'
  File "/Users/rankor/src/python/VideoMaker2/.venv/lib/python3.7/site-packages/odnoklassniki/api.py", line 84, in __call__
    return self._get(self._method, **kwargs)
  File "/Users/rankor/src/python/VideoMaker2/.venv/lib/python3.7/site-packages/odnoklassniki/api.py", line 51, in _get
    status, response = self._request(method, **kwargs)
  File "/Users/rankor/src/python/VideoMaker2/.venv/lib/python3.7/site-packages/odnoklassniki/api.py", line 118, in _request
    return req.status_code, req.json()
  File "/Users/rankor/src/python/VideoMaker2/.venv/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sidanya** [comment]
так и не дождался ответа
